config/routes.rb
Rails.application.routes.draw do

  #devise初期設定
  devise_for :users

  #1 予めメインのモデル・コントローラー作成する
  # コントローラーで indexアクションを定義（空欄）
  root to: 'tweets#index'#ここがtop pageとなる
  
  #2 基本の７つのアクションのみ
  # resources :tweets
  # 学習用↓
  # resources :tweets, only: [:index, :new]

  
  #3 検索の機能を追加
  resources :tweets do
    resources :comments, only: :create #pic2での記述参考
    #↑ルーティングのネストと言う

    #検索用
    collection do
      get 'kensaku'
    end
  end
  

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ActiveHash::Base
  self.data = [
    { id: 1, name: 'ピンク' },
    { id: 2, name: 'グリーン' },
    { id: 3, name: 'ダーク' },
    { id: 4, name: 'スカイ' }
  ]
  end
  

app/models/comment.rb
class Comment < ApplicationRecord

  #アソシエーション
  belongs_to :tweet
  belongs_to :user

end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '回答しない' },
    { id: 2, name: '女性' },
    { id: 3, name: '男性' }
  ]
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  #2 active storage用
  has_one_attached :image
  #↑を記述したらコントローラーで保存の許可をする

  
  #3 アソシエーション
  belongs_to :user
  has_many :comments


  #1
  validates :text, presence: true, unless: :was_attached?
  #2 ↑unless: :was_attached?は画像のみでも投稿できるように
  def was_attached?
    self.image.attached?
  end


  #4検索機能
  def self.search(naiyou) #引数に検索の入力内容が入る
    if naiyou
      Tweet.where('text LIKE(?)', "%#{naiyou}%")
    else
      Tweet.all #無入力で全部？
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #↓必要に応じて機能を追加
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :timeoutable, :trackable
  #最初は認証無しで実装

  #アソシエーション
  has_many :tweets
  has_many :comments

  
  validates :name, :kana, :birth, :gender, :nick_name, :color, presence: true
  

  #active hash
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :gender
  belongs_to_active_hash :color
  #DBの型がstringあるいはからむ名に_idがついて無いなどでエラーになったことある


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  #devise userテーブルのカラム保存許可
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :kana, :birth, :gender_id, :nick_name, :color_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    #pic2参考の通常のコメント投稿
    #comment = Comment.create(comment_params)
    #redirect_to "/tweets/#{comment.tweet.id}"

    
    #action cable
    #1 以下の1行のみ
    @comment = Comment.new(msg: params[:comment][:msg])

    #2 channel作成後
    # メッセージの保存が成功したときに、broadcastを介してメッセージが送信されるように記述
    if Comment.create(comment_params)
      ActionCable.server.broadcast 'comment_channel', content: @comment
      # broadcastを通して、'comment_channel'に向けて@commentを送信する
    end
    # 送信された情報は、comment_channel.jsで受け取り

  end

  private
  def comment_params
    params.require(:comment).permit(:msg).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]#6
  before_action :move_to_index, except: [:index, :show, :kensaku]

  def index#1
    #@tweets = Tweet.all#1-1
    #@tweets = Tweet.all.order("created_at DESC")#1-2
    @tweets = Tweet.includes(:user).order("created_at DESC")#1-3
  end

  def new#2
    @tweet = Tweet.new
  end

  def create#3    
    #Tweet.create(tweet_params)#3-1
    @tweet = Tweet.new(tweet_params)#3-2
    if @tweet.save
      redirect_to root_path
    else
      flash[:not_input] = "何も入力されていません。"
      render :new
    end
  end

  def destroy#5
    tweet = Tweet.find(params[:id])
    #binding.pry #検証用
    tweet.destroy

    redirect_to root_path, notice: '投稿が削除されました。'
  end

  def edit#6  
  end

  def update#7
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to tweet_path(params[:id]), notice: '投稿が更新されました。'
    else
      flash[:not_input] = "何も入力されていません。"
      render :edit
    end
  end

  
  def show#6
    #comment機能を追加してからの記述
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)

  end


  def kensaku
    #render plain: "kensakuアクションが動作した" #動作確認用
    #binding.pry #検証用 (ターミナルで"params"と入れるとデータ確認できる)
    @tweets = Tweet.search(params[:key_wd])
    #インスタンス変数 = モデル.メソッド(検索内容)→モデル内のメソッド呼び出し

    @key_wd = (params[:key_wd])#userの入力内容を取得(view表示用)

  end


  private

  def tweet_params#4
    params.require(:tweet).permit(:text, :image).merge(user_id: current_user.id)
    # :imageはactive storage用
    #.merge(user_id: current_user.id)はuser機能追加後に記述
  end

  def set_tweet#6
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    /responsive
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", name: "viewport"}
    /web font
    %link{:href => "https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap", :rel => "stylesheet"}/

    %title MixApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  
  %body
  /-------------------------------------------------------------------------------------------

  %header
    .main_logo
      %a.main_logo{:href => "/"} Mix_app

    .notice
      = notice#コントローラーからのメッセージ
    .alert
      = alert#deviseのメッセージ有

    .search_bar
      = form_with(url: kensaku_tweets_path, local: true, method: :get, class: "search_form")do |x|

        = x.text_field :key_wd, placeholder:"検索する",size:8, autocomplete: "off", class: "search_input"
        = x.submit "探す", class: "search_btn"


    .header_menu.mobile_menu#mo_menu
      /user機能追加前の記述
      /= link_to "投稿する", new_tweet_path, class: "menu_btn"
      -if user_signed_in?
        = link_to "投稿する", new_tweet_path, class: "menu_btn"
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "menu_btn"
        = link_to "こんにちは。#{current_user.nick_name}さん！", edit_user_registration_path, class: "menu_btn"
      -else
        = link_to "ログイン", new_user_session_path, class: "menu_btn"
        = link_to "新規登録", new_user_registration_path, class: "menu_btn"
    
    .mobile_menu_btn#mo_menu_btn
      %p MENU    
  /--------------------------------------------------------------------------------------
  
  .main_content
    .left_main_menu
      %p ここはメインメニュー。(app...html.hamlの左側)

    .rigth_content
      = yield

  
  %footer
    .notice
      %p ここはフッターです。

app/views/tweets/_twt.html.haml
.content_card
  .inner_menu
    /for test
    /%p.inner_btn ボタン1

    .inner_name
      %p= "#{xyz.user.nick_name}さん"
          
    .inner_btns
      = link_to '詳細', tweet_path(xyz.id),method: :get, class: 'inner_btn'

      - if user_signed_in? && current_user.id == xyz.user_id
        = link_to '編集', edit_tweet_path(xyz.id),method: :get, class: 'inner_btn'          
        = link_to '削除', tweet_path(xyz.id),method: :delete, class: 'inner_btn'

  .content_text
    %p= simple_format(xyz.text)
    / simple_format で改行などをそのまま表示

  .content_img
    = image_tag xyz.image.variant(resize:'320x240') if xyz.image.attached?

app/views/tweets/create.html.haml
/ここは未使用。基本動作確認時の為にとっておく
.content_done
  %h3 投稿完了しました。
  %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/tweets/edit.html.haml
.content_post
  = form_with(model: @tweet, local: true) do |form|

        
    .post_mes
      %h3 ここはedit.html.haml
      %p.notice= flash[:not_input]#コントローラーからのメッセージ
      = form.text_area :text, placeholder: "コメントを書いてください", rows: "10", class: "mes_inner"
      
    .post_img
      = form.file_field :image
      %p 画像の変更が無い場合はそのまま更新
      
    .post_btn
      = form.submit "更新"


  .content_img
    %p 現在の画像
    = image_tag @tweet.image.variant(resize:'640x480') if @tweet.image.attached?

    

app/views/tweets/index.html.haml
.content_view
  .content_title
    %p メインコンテンツ(index.html.haml)
  
  .content_inner
    - @tweets.each do |tweet|
      /= render "twt", xyz: tweet #部分テンプレ
      /= render "呼び出し先", 呼出先用変数: ここのブロック変数

      
      /学習用・部分テンプレ導入前
      .content_card
        .inner_menu
          /for test
          /%p.inner_btn ボタン1

          .inner_name
            %p= "#{tweet.user.nick_name}さん"
          
          .inner_btns
            = link_to '詳細', tweet_path(tweet.id),method: :get, class: 'inner_btn'

            - if user_signed_in? && current_user.id == tweet.user_id
              = link_to '編集', edit_tweet_path(tweet.id),method: :get, class: 'inner_btn'          
              = link_to '削除', tweet_path(tweet.id),method: :delete, class: 'inner_btn'

        .content_text
          %p= simple_format(tweet.text)
          / simple_format で改行などをそのまま表示

        .content_img
          = image_tag tweet.image.variant(resize:'320x240') if tweet.image.attached?

app/views/tweets/kensaku.html.haml
.content_view
  .content_title
    %p= "「#{@key_wd}」の検索結果"
  
  .content_inner
    - @tweets.each do |tweet|
      = render "twt", xyz: tweet
      /= render "呼び出し先", 呼出先用変数: ここのブロック変数

app/views/tweets/new.html.haml
.content_post
  = form_with(model: @tweet, local: true) do |form|
      
    .post_mes
      %h3 ここは投稿するページです
      %p.notice= flash[:not_input]#コントローラーからのメッセージ
      = form.text_area :text, placeholder: "コメントを書いてください", rows: "10", class: "mes_inner"
      
    .post_img
      = form.file_field :image
      
    .post_btn
      = form.submit "送信"

    

app/views/tweets/show.html.haml
.content_view

  .content_inner
    .content_card_show
      .inner_menu

        .inner_name
          %p= "#{@tweet.user.nick_name}さん"
          
        .inner_btns
          - if user_signed_in? && current_user.id == @tweet.user_id
            = link_to '編集', edit_tweet_path(@tweet.id),method: :get, class: 'inner_btn'          
            = link_to '削除', tweet_path(@tweet.id),method: :delete, class: 'inner_btn'

      .content_text_show
        %p= simple_format(@tweet.text)
        / simple_format で改行などをそのまま表示

    .content_img_pc
      = image_tag @tweet.image.variant(resize:'640x480') if @tweet.image.attached?
    .content_img_mobile
      = image_tag @tweet.image.variant(resize:'384x288') if @tweet.image.attached?

    %p= "最終更新日：#{@tweet.updated_at}"

    /通常のコメント機能
    .content_msg

      - if current_user
        = form_with(model: [@tweet, @comment], local: true) do |f|
          =f.text_area :msg, placeholder: "コメントをどうぞ", rows: "2"
          =f.submit "コメントを書く（削除出来ません。）"
      - else
        %p ログインをするとコメントを残せるよ！
      
      .msg_all
        - if @comments
          - @comments.each do |cmt|
            %p= "#{cmt.user.nick_name}：#{cmt.msg}"
    
    /action cable
    .content_msg2

      - if current_user
        %p こっちは action cable機能
        = form_with(model: [@tweet, @comment], local: true) do |x|        
          =x.text_field :msg, autocomplete: "off"
          =x.submit "即書く（こっちも削除出来ません。）"
      - else
        %p ログインをするとコメントを残せるよ！
      
      .msg_all#messages
        - if @comments
          - @comments.reverse_each do |cmt|
            %p= "#{cmt.user.nick_name}：#{cmt.msg}"